# Generated by Django 4.1.7 on 2023-04-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('wattsapp', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipCode', models.CharField(max_length=100)),
                ('contactShare', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=100)),
                ('Allergy', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Dust', 'Dust'), ('None', 'None')], max_length=100)),
                ('daysAttending', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thrusday', 'Thrusday'), ('Friday', 'Frinday'), ('Saturday', 'Saturday')], max_length=100)),
                ('activities', models.CharField(choices=[('Feeding drives', 'Feeding drives'), ('Sterilization process', 'Sterilization process'), ('Adoption help', 'Adoption help'), ('digital awarness', 'digital awarness'), ('vaccination helping', 'vaccination helping')], max_length=100)),
                ('about', models.TextField(max_length=100)),
            ],
        ),
    ]
